//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GServer.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GSERVETYPE                  129
#define IDD_NETWORK                     130
#define IDB_CORTEK_LOGO                 138
#define IDD_DEVICE_SETUP                140
#define IDB_MODULE_DISABLED             141
#define IDB_CIRCUIT_1                   146
#define IDB_SOFTBLUE_1                  148
#define IDB_MODULE_NA                   151
#define IDB_MODULE_INPUT                152
#define IDB_MODULE_MASTER               153
#define IDB_MODULE_AUX                  154
#define IDB_MODULE_COMPUTER             155
#define IDR_MENU_MODULESELECTION        157
#define IDB_VERDE                       159
#define IDB_MODULE_MATRIX               160
#define IDB_MODULE_CUE                  161
#define IDB_CLIP                        165
#define IDB_NO_CLIP                     166
#define IDD_DIALOG1                     168
#define IDB_MODULE_NA_VU                174
#define IDB_MODULE_INPUT_VU             175
#define IDB_MODULE_AUX_VU               176
#define IDB_MODULE_MATRIX_VU            177
#define IDB_MODULE_CUE_VU               178
#define IDB_MODULE_MASTER_VU            179
#define IDB_BITMAP1                     180
#define IDS_TBNAME_GENERAL              200
#define IDS_TBNAME_VIEWS                201
#define IDS_NET_ERROR_MSG               300
#define IDS_NET_ERROR_INVALIDHEADER     301
#define IDS_NETMSG_NOT_IMPLEMET         400
#define IDS_SERVER_SHUTDOWN             500
#define IDS_SERVER_STARTED              501
#define IDS_SERVER_FAILEDTOSTART        502
#define IDS_MAX_CONNECTIONS             503
#define IDS_CONNECTION_CLOSED           504
#define IDS_CLIENT_STARTED              600
#define IDS_CLIENT_FAILEDTOSTART        601
#define IDS_CONVERSION_ERROR            700
#define IDS_DCXTABLE_LOAD_ERROR         701
#define IDS_DCX_CONTROLREMAP_ERROR      702
#define IDS_DCX_CONTROLSEL_INVALID      703
#define IDS_CONVERSION_DONE             704
#define DCXDEV_ERROR_WRITE              1000
#define DCXDEV_ERROR_READ               1001
#define IDC_TCP_ADDRESS                 1002
#define IDC_TCP_PORT                    1003
#define IDC_CHK_NET_SERVER              1005
#define IDC_NETMON_BYTESOUT             1007
#define IDC_NETMON_BYTESIN              1008
#define IDC_DCXCTRLS_MODULEADDR         1008
#define IDC_DCXCTRS_SETADDR             1009
#define IDC_DCXCTRLS_RESETBUS           1010
#define IDC_CTRLS_LIST                  1011
#define IDC_CTRLS_SLIDER                1012
#define IDC_CTRLS_RDOUT                 1013
#define IDC_CTRLS_NAME                  1014
#define IDC_CTRLS_DELAY                 1015
#define IDC_CTRLS_ACTIVATEAUTO          1016
#define IDC_CONV_DESTINATION            1017
#define IDC_CONV_LOAD                   1018
#define IDC_CONV_SOURCE                 1019
#define IDC_CONV_GO                     1020
#define IDC_CONV_REVERSE_CTRLVALUES     1021
#define IDC_NET_MSG_LIST                1024
#define IDC_MESSAGES_CLEAR              1033
#define IDC_CLIP1                       1058
#define IDC_CLIP3                       1059
#define IDC_CLIP5                       1060
#define IDC_CLIP7                       1061
#define IDC_CLIP2                       1062
#define IDC_CLIP4                       1063
#define IDC_CLIP6                       1064
#define IDC_CLIP8                       1065
#define IDC_CLIP_RESET                  1066
#define IDC_SET_ZERO_REG                1067
#define IDC_LIST1                       1068
#define IDC_LIST2                       1069
#define IDC_FILENAME                    1070
#define IDC_BROWSE                      1071
#define ID_DOWNLOAD                     1072
#define IDC_ADDRESS                     1073
#define ID_CLOSE                        1074
#define IDC_ALL_MODULES                 1075
#define IDC_MONITOR_ONOFF               1076
#define IDT_COMPANY_NAME                1077
#define IDT_FILE_DESC                   1078
#define IDT_PROD_VER                    1079
#define IDT_COPYRIGHT                   1080
#define IDT_TRADEMARKS                  1081
#define IDC_NUM_CONNECTIONS             1082
#define IDC_NUM_CLIENTS_TEXT            1083
#define ID_VIEW_NETWORK                 32771
#define ID_VIEW_CONVERTER               32772
#define ID_VIEW_CONTROLS                32773
#define ID_VIEW_DEVICE                  32774
#define ID_INPUTMODULE                  32814
#define ID_AUXMODULE                    32815
#define ID_MATRIXMODULE                 32816
#define ID_CUEMODULE                    32817
#define ID_MASTERMODULE                 32818
#define ID_NATYPE                       32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
